import type {
  Imovel, Marca, ProdutoMarca, EncaixePerfeito,
  Empreendimento, AssetOS, EstrategiaOS, DesignSystemOS,
  ProdutoIndustria, ExclusividadeRegra, EspecificacaoArquiteto,
  ProjetoArquiteto, MetricaAdTech, HubMetrica,
} from "./types";

export const MOCK_IMOVEIS: Imovel[] = [
  {
    id: "imv-001",
    titulo: "Apartamento Alto Padrão — Jardins",
    bairro: "Jardins",
    cidade: "São Paulo",
    tipo: "APARTAMENTO",
    padrao: "ALTO",
    status: "TURBINADO",
    preco: 1_850_000,
    area: 145,
    quartos: 3,
    banheiros: 3,
    vagas: 2,
    descricao: "Apartamento completamente reformado com acabamentos de alto padrão. Vista panorâmica, varanda gourmet e ambientes integrados.",
    imagens: ["/mock/apto-jardins-1.jpg", "/mock/apto-jardins-2.jpg"],
    score_ia: 94,
    criado_em: "2024-05-10",
    atualizado_em: "2024-06-01",
  },
  {
    id: "imv-002",
    titulo: "Cobertura Duplex — Itaim Bibi",
    bairro: "Itaim Bibi",
    cidade: "São Paulo",
    tipo: "COBERTURA",
    padrao: "LUXO",
    status: "PUBLICADO",
    preco: 4_200_000,
    area: 280,
    quartos: 4,
    banheiros: 5,
    vagas: 3,
    descricao: "Cobertura duplex com piscina privativa, churrasqueira e terraço de 80m². Vista 360° da cidade.",
    imagens: ["/mock/cobertura-itaim-1.jpg"],
    score_ia: 98,
    criado_em: "2024-04-22",
    atualizado_em: "2024-05-30",
  },
  {
    id: "imv-003",
    titulo: "Casa de Campo Moderna — Alphaville",
    bairro: "Alphaville",
    cidade: "Barueri",
    tipo: "CASA",
    padrao: "ALTO",
    status: "TURBINADO",
    preco: 2_650_000,
    area: 380,
    quartos: 5,
    banheiros: 6,
    vagas: 4,
    descricao: "Casa contemporânea em condomínio fechado de alto padrão. Jardim projetado por paisagista renomado e automação residencial completa.",
    imagens: ["/mock/casa-alphaville-1.jpg"],
    score_ia: 87,
    criado_em: "2024-05-15",
    atualizado_em: "2024-06-05",
  },
  {
    id: "imv-004",
    titulo: "Apartamento Studio — Pinheiros",
    bairro: "Pinheiros",
    cidade: "São Paulo",
    tipo: "APARTAMENTO",
    padrao: "MEDIO",
    status: "PUBLICADO",
    preco: 480_000,
    area: 42,
    quartos: 1,
    banheiros: 1,
    vagas: 1,
    descricao: "Studio compacto e bem localizado, próximo ao metrô. Ideal para jovens profissionais.",
    imagens: ["/mock/studio-pinheiros-1.jpg"],
    score_ia: 71,
    criado_em: "2024-06-01",
    atualizado_em: "2024-06-10",
  },
  {
    id: "imv-005",
    titulo: "Apartamento 2 Dormitórios — Vila Madalena",
    bairro: "Vila Madalena",
    cidade: "São Paulo",
    tipo: "APARTAMENTO",
    padrao: "MEDIO",
    status: "RASCUNHO",
    preco: 720_000,
    area: 68,
    quartos: 2,
    banheiros: 2,
    vagas: 1,
    descricao: "Apartamento em prédio boutique no coração da Vila Madalena. Acabamentos de qualidade e excelente localização.",
    imagens: [],
    score_ia: 0,
    criado_em: "2024-06-12",
    atualizado_em: "2024-06-12",
  },
  {
    id: "imv-006",
    titulo: "Penthouse — Moema",
    bairro: "Moema",
    cidade: "São Paulo",
    tipo: "APARTAMENTO",
    padrao: "LUXO",
    status: "PUBLICADO",
    preco: 5_800_000,
    area: 320,
    quartos: 4,
    banheiros: 5,
    vagas: 3,
    descricao: "Penthouse exclusivo com project de interiores assinado. Pé-direito duplo e materiais importados.",
    imagens: ["/mock/penthouse-moema-1.jpg"],
    score_ia: 96,
    criado_em: "2024-03-18",
    atualizado_em: "2024-05-22",
  },
  {
    id: "imv-007",
    titulo: "Sala Comercial Premium — Faria Lima",
    bairro: "Faria Lima",
    cidade: "São Paulo",
    tipo: "COMERCIAL",
    padrao: "ALTO",
    status: "TURBINADO",
    preco: 1_100_000,
    area: 95,
    quartos: 0,
    banheiros: 2,
    vagas: 2,
    descricao: "Sala comercial no principal eixo financeiro de São Paulo. Acabamento AA+ com vista privilegiada.",
    imagens: ["/mock/sala-faria-lima-1.jpg"],
    score_ia: 82,
    criado_em: "2024-05-28",
    atualizado_em: "2024-06-08",
  },
  {
    id: "imv-008",
    titulo: "Casa Térrea — Morumbi",
    bairro: "Morumbi",
    cidade: "São Paulo",
    tipo: "CASA",
    padrao: "ALTO",
    status: "VENDIDO",
    preco: 3_400_000,
    area: 450,
    quartos: 5,
    banheiros: 6,
    vagas: 4,
    descricao: "Casa térrea com amplo jardim, piscina e área de lazer completa. Totalmente reformada.",
    imagens: ["/mock/casa-morumbi-1.jpg"],
    score_ia: 91,
    criado_em: "2024-02-10",
    atualizado_em: "2024-06-15",
  },
];

export const MOCK_MARCAS: Marca[] = [
  {
    id: "mrc-001",
    nome: "Portobello",
    categoria: "Pisos & Revestimentos",
    logo_url: "/mock/logo-portobello.svg",
    score_compatibilidade: 96,
    produtos_disponiveis: 48,
    campanha_ativa: true,
  },
  {
    id: "mrc-002",
    nome: "Deca",
    categoria: "Louças & Metais",
    logo_url: "/mock/logo-deca.svg",
    score_compatibilidade: 91,
    produtos_disponiveis: 34,
    campanha_ativa: true,
  },
  {
    id: "mrc-003",
    nome: "Poliform",
    categoria: "Mobiliário de Design",
    logo_url: "/mock/logo-poliform.svg",
    score_compatibilidade: 88,
    produtos_disponiveis: 22,
    campanha_ativa: true,
  },
  {
    id: "mrc-004",
    nome: "Intelbras",
    categoria: "Automação Residencial",
    logo_url: "/mock/logo-intelbras.svg",
    score_compatibilidade: 79,
    produtos_disponiveis: 15,
    campanha_ativa: false,
  },
  {
    id: "mrc-005",
    nome: "Eliane",
    categoria: "Pisos & Revestimentos",
    logo_url: "/mock/logo-eliane.svg",
    score_compatibilidade: 74,
    produtos_disponiveis: 61,
    campanha_ativa: true,
  },
];

export function getEncaixePerfeito(imovelId: string): EncaixePerfeito[] {
  const imovel = MOCK_IMOVEIS.find((i) => i.id === imovelId);
  if (!imovel) return [];

  const sugestoes: EncaixePerfeito[] = [
    {
      marca: MOCK_MARCAS[0],
      motivo: `Padrão ${imovel.padrao} tem alta taxa de conversão com Portobello no ${imovel.bairro}`,
      categorias_match: ["Pisos", "Revestimentos"],
      score: 96,
    },
    {
      marca: MOCK_MARCAS[1],
      motivo: `${imovel.banheiros} banheiros aumentam o ROI de Louças & Metais em ${imovel.bairro}`,
      categorias_match: ["Louças", "Metais Sanitários"],
      score: 91,
    },
    {
      marca: MOCK_MARCAS[2],
      motivo: `${imovel.area}m² e ${imovel.quartos} ambientes são o perfil ideal para Poliform`,
      categorias_match: ["Mobiliário", "Cozinha"],
      score: 88,
    },
  ];

  return sugestoes;
}

export function formatCurrency(value: number): string {
  return new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
    maximumFractionDigits: 0,
  }).format(value);
}

export const DASHBOARD_STATS = {
  total_imoveis: 24,
  imoveis_turbinados: 8,
  leads_gerados: 47,
  marcas_ativas: 3,
  receita_estimada: 12_400,
  views_mes: 1_842,
};

// ─── TAGMOB OS ────────────────────────────────────────────────────────────────

export const MOCK_EMPREENDIMENTOS: Empreendimento[] = [
  {
    id: "emp-001",
    nome: "Reserva Jardins",
    tipo: "RESIDENCIAL",
    construtora: "Tegra Incorporadora",
    bairro: "Jardins",
    cidade: "São Paulo",
    fase_atual: 4,
    status: "EM_ANDAMENTO",
    plano: "ENTERPRISE",
    assinatura_ativa: true,
    cor_tema: "#FF0068",
    thumbnail_url: "",
    criado_em: "2024-03-10",
    estrategia_completa: true,
    criacao_completa: true,
    total_assets: 24,
    assets_aprovados: 18,
    assets_pendentes: 6,
  },
  {
    id: "emp-002",
    nome: "Faria Lima Corporate",
    tipo: "COMERCIAL",
    construtora: "Brookfield Incorporações",
    bairro: "Faria Lima",
    cidade: "São Paulo",
    fase_atual: 3,
    status: "EM_ANDAMENTO",
    plano: "PRO",
    assinatura_ativa: true,
    cor_tema: "#8B5CF6",
    thumbnail_url: "",
    criado_em: "2024-04-05",
    estrategia_completa: true,
    criacao_completa: true,
    total_assets: 16,
    assets_aprovados: 7,
    assets_pendentes: 9,
  },
  {
    id: "emp-003",
    nome: "Vista Verde Moema",
    tipo: "RESIDENCIAL",
    construtora: "Even Construtora",
    bairro: "Moema",
    cidade: "São Paulo",
    fase_atual: 2,
    status: "EM_ANDAMENTO",
    plano: "PRO",
    assinatura_ativa: true,
    cor_tema: "#00E5FF",
    thumbnail_url: "",
    criado_em: "2024-05-12",
    estrategia_completa: true,
    criacao_completa: false,
    total_assets: 0,
    assets_aprovados: 0,
    assets_pendentes: 0,
  },
  {
    id: "emp-004",
    nome: "Alphaville Signature",
    tipo: "RESIDENCIAL",
    construtora: "Alphaville Urbanismo",
    bairro: "Alphaville",
    cidade: "Barueri",
    fase_atual: 5,
    status: "PUBLICADO",
    plano: "ENTERPRISE",
    assinatura_ativa: true,
    cor_tema: "#39FF14",
    thumbnail_url: "",
    criado_em: "2024-01-20",
    estrategia_completa: true,
    criacao_completa: true,
    total_assets: 42,
    assets_aprovados: 42,
    assets_pendentes: 0,
  },
  {
    id: "emp-005",
    nome: "Pinheiros Lofts",
    tipo: "MISTO",
    construtora: "Cyrela Commercial Properties",
    bairro: "Pinheiros",
    cidade: "São Paulo",
    fase_atual: 1,
    status: "EM_ANDAMENTO",
    plano: "STARTER",
    assinatura_ativa: true,
    cor_tema: "#FFB800",
    thumbnail_url: "",
    criado_em: "2024-06-01",
    estrategia_completa: false,
    criacao_completa: false,
    total_assets: 0,
    assets_aprovados: 0,
    assets_pendentes: 0,
  },
];

export const MOCK_ESTRATEGIA: Record<string, EstrategiaOS> = {
  "emp-001": {
    empreendimento_id: "emp-001",
    pesquisa_mercado: "Análise de 47 empreendimentos concorrentes no segmento Alto Padrão nos Jardins. Ticket médio de R$2,8M. Público-alvo: famílias AB+ com 35-55 anos. Principal driver de decisão: localização (78%) e projeto arquitetônico (64%).",
    naming: "**Reserva Jardins** — Evoca exclusividade por meio da ideia de reserva/preservação. A palavra 'jardins' ancora territorialmente sem ser literal. Sonoridade: 4 sílabas, fluida e premium.",
    conceito_criativo: "**'O espaço que você reserva para o que importa.'** — Conceito centrado na curadoria de vida, não no imóvel. A ideia de que escolher este endereço é um ato de intenção, não só de compra.",
    manifesto: "Há lugares que não se encontram. Se reservam.\n\nReserva Jardins não é um apartamento. É a declaração mais silenciosa que você pode fazer sobre como escolheu viver. Em cada detalhe, a riqueza de quem sabe que o essencial ocupa espaço — e que o tempo de qualidade começa onde termina o barulho do mundo.",
    tom_de_voz: ["Sofisticado sem ser distante", "Seguro sem ser arrogante", "Poético sem ser vago", "Direto sem ser frio"],
    argumentos_venda: ["245m² de planta livre customizável", "Apenas 4 apartamentos por andar", "Varanda de 32m² com vista para o verde", "Sistema de automação Loxone integrado", "3 vagas privativas + lavagem gratuita"],
    publico_alvo: "Executivos e empreendedores 38-58 anos, classe AB, que já possuem imóvel próprio e buscam elevar o padrão de moradia. Valorizam privacidade, design e localização acima de área.",
    posicionamento: "O apartamento de menor quantidade e maior densidade de significado no bairro mais valorizado de São Paulo.",
    completo: true,
  },
  "emp-002": {
    empreendimento_id: "emp-002",
    pesquisa_mercado: "Levantamento de absorção de lajes corporativas na Faria Lima. Vacância atual: 8,2%. Demanda por espaços menores (200-500m²) cresceu 34% em 2023. Perfil locatário: fintechs, consultorias e gestoras.",
    naming: "**Faria Lima Corporate** — Naming direto e assertivo para o B2B. Ancora no endereço mais valorioso do mercado corporativo paulistano.",
    conceito_criativo: "**'Onde as decisões têm endereço.'** — Para empresas que entendem que o endereço comunica antes de qualquer reunião.",
    manifesto: "Endereço é estratégia.\n\nFaria Lima Corporate não oferece apenas infraestrutura. Oferece posicionamento. Quando seu escritório está aqui, a conversa começa antes de você entrar na sala.",
    tom_de_voz: ["Corporativo e direto", "Orientado a resultados", "Sem floreios", "Confiança de longa data"],
    argumentos_venda: ["Lajes de 250 a 1.200m²", "Certificação LEED Gold", "Gerador 100% da carga elétrica", "Fibra ótica dedicada 10Gbps", "Estacionamento rotativo integrado"],
    publico_alvo: "Empresas mid-market e scale-ups com 50-500 funcionários, buscando endereço premium na Faria Lima para sede ou filial.",
    posicionamento: "O escritório que trabalha pelo seu negócio antes mesmo de você abrir a porta.",
    completo: true,
  },
};

export const MOCK_DESIGN_SYSTEM: Record<string, DesignSystemOS> = {
  "emp-001": {
    empreendimento_id: "emp-001",
    key_visual_descricao: "Fotografia arquitetônica minimalista com tratamento de cor verde-musgo e off-white. Elementos tipográficos serifados em fino peso (Cormorant Garamond Light). Composição com espaço negativo generoso.",
    paleta_cores: [
      { nome: "Verde Reserva",  hex: "#3D5A3E" },
      { nome: "Off-White Puro", hex: "#F8F5EF" },
      { nome: "Cobre Escuro",   hex: "#8B6A3E" },
      { nome: "Grafite Suave",  hex: "#2C2C2C" },
      { nome: "Creme",          hex: "#EDE8DF" },
    ],
    fontes: [
      { nome: "Cormorant Garamond", uso: "Títulos e assinaturas — elegância e peso histórico" },
      { nome: "DM Sans",            uso: "Corpo de texto e tabelas — legibilidade contemporânea" },
      { nome: "Freight Display",    uso: "Headlines de impacto — exclusivo para OOH" },
    ],
    logo_principal: "RJ_logo_principal.svg",
    grid_descricao: "Grid de 12 colunas com margem de 48px. Bloco fotográfico sempre em 8 colunas. Área de texto em 4 colunas com alinhamento à direita.",
    completo: true,
  },
};

export const MOCK_ASSETS: AssetOS[] = [
  {
    id: "ast-001",
    empreendimento_id: "emp-001",
    nome: "Post Instagram — Lançamento",
    tipo: "INSTAGRAM_POST",
    descricao: "Post quadrado de lançamento com headline principal e CTA de cadastro",
    status: "APROVADO",
    bloqueado: true,
    aprovado_agencia_em: "2024-05-20T14:30:00Z",
    aprovado_agencia_por: "Ana Lima — TAGMOB",
    aprovado_cliente_em: "2024-05-21T09:15:00Z",
    aprovado_cliente_por: "Ricardo Souza — Tegra",
    comentarios: [],
    campos_editaveis: [
      { id: "f1", label: "Preço a partir de",    tipo: "PRECO",  valor_atual: "R$ 2.400.000",   placeholder: "R$ 0.000.000", max_chars: 20 },
      { id: "f2", label: "CTA Principal",         tipo: "CTA",   valor_atual: "AGENDE SUA VISITA", placeholder: "Digite o CTA", max_chars: 28 },
      { id: "f3", label: "Data do Evento",         tipo: "TEXTO", valor_atual: "28 e 29 de Junho", placeholder: "DD e DD de Mês", max_chars: 24 },
    ],
    dimensoes: "1080 × 1080px",
    criado_em: "2024-05-18",
  },
  {
    id: "ast-002",
    empreendimento_id: "emp-001",
    nome: "Story — Countdown Lançamento",
    tipo: "STORY",
    descricao: "Story vertical com contador regressivo para o evento de lançamento",
    status: "APROVADO",
    bloqueado: true,
    aprovado_agencia_em: "2024-05-20T14:35:00Z",
    aprovado_agencia_por: "Ana Lima — TAGMOB",
    aprovado_cliente_em: "2024-05-21T09:20:00Z",
    aprovado_cliente_por: "Ricardo Souza — Tegra",
    comentarios: [],
    campos_editaveis: [
      { id: "f1", label: "Dias restantes", tipo: "TEXTO", valor_atual: "3",  placeholder: "0", max_chars: 3 },
      { id: "f2", label: "Subtítulo",      tipo: "TEXTO", valor_atual: "Para o lançamento exclusivo", placeholder: "Subtítulo do countdown", max_chars: 40 },
    ],
    dimensoes: "1080 × 1920px",
    criado_em: "2024-05-18",
  },
  {
    id: "ast-003",
    empreendimento_id: "emp-001",
    nome: "PDF Gráfica — Folheto A4",
    tipo: "PDF_GRAFICA",
    descricao: "Folheto A4 frente e verso para entrega em stand de vendas",
    status: "AGUARDANDO_CLIENTE",
    bloqueado: true,
    aprovado_agencia_em: "2024-05-22T11:00:00Z",
    aprovado_agencia_por: "Ana Lima — TAGMOB",
    aprovado_cliente_em: null,
    aprovado_cliente_por: null,
    comentarios: [
      {
        id: "c1",
        autor: "Ana Lima",
        perfil: "AGENCIA",
        mensagem: "Folheto enviado para aprovação final. Atenção: verso com planta e tabela de áreas.",
        criado_em: "2024-05-22T11:05:00Z",
      },
    ],
    campos_editaveis: [
      { id: "f1", label: "Preço unidades tipo",    tipo: "PRECO",  valor_atual: "A partir de R$ 2.400.000", placeholder: "A partir de R$ 0.000.000", max_chars: 35 },
      { id: "f2", label: "Metragem min.",           tipo: "TEXTO",  valor_atual: "a partir de 198m²",       placeholder: "a partir de Xm²",           max_chars: 20 },
      { id: "f3", label: "Contato do corretor",     tipo: "TEXTO",  valor_atual: "(11) 99999-0000",         placeholder: "(11) 00000-0000",            max_chars: 20 },
    ],
    dimensoes: "210 × 297mm + 3mm sangria",
    criado_em: "2024-05-21",
  },
  {
    id: "ast-004",
    empreendimento_id: "emp-001",
    nome: "Banner Digital — Portal Imóveis",
    tipo: "BANNER_DIGITAL",
    descricao: "Banner em múltiplos formatos para veiculação em portais imobiliários",
    status: "AGUARDANDO_AGENCIA",
    bloqueado: true,
    aprovado_agencia_em: null,
    aprovado_agencia_por: null,
    aprovado_cliente_em: null,
    aprovado_cliente_por: null,
    comentarios: [
      {
        id: "c1",
        autor: "Lucas Mendes",
        perfil: "CLIENTE",
        mensagem: "Precisamos destacar mais o número de vagas de garagem. O concorrente usa isso como diferencial.",
        criado_em: "2024-05-23T16:22:00Z",
      },
    ],
    campos_editaveis: [
      { id: "f1", label: "Headline",   tipo: "TEXTO", valor_atual: "O espaço que você reserva", placeholder: "Headline principal", max_chars: 40 },
      { id: "f2", label: "Subheadline",tipo: "TEXTO", valor_atual: "para o que importa.",       placeholder: "Subheadline",        max_chars: 40 },
    ],
    dimensoes: "300×250 / 728×90 / 160×600",
    criado_em: "2024-05-23",
  },
  {
    id: "ast-005",
    empreendimento_id: "emp-001",
    nome: "Vídeo Reels — Tour do Apartamento",
    tipo: "VIDEO_REELS",
    descricao: "Vídeo de 30s do tour pelo apartamento decorado com narração em off",
    status: "RASCUNHO",
    bloqueado: true,
    aprovado_agencia_em: null,
    aprovado_agencia_por: null,
    aprovado_cliente_em: null,
    aprovado_cliente_por: null,
    comentarios: [],
    campos_editaveis: [
      { id: "f1", label: "Texto de abertura", tipo: "TEXTO", valor_atual: "Reserva Jardins", placeholder: "Nome do empreendimento", max_chars: 30 },
    ],
    dimensoes: "1080 × 1920px · 30s",
    criado_em: "2024-05-24",
  },
  // emp-002 assets
  {
    id: "ast-010",
    empreendimento_id: "emp-002",
    nome: "Post LinkedIn — Lajes Disponíveis",
    tipo: "INSTAGRAM_POST",
    descricao: "Post para LinkedIn comunicando disponibilidade de lajes",
    status: "AGUARDANDO_CLIENTE",
    bloqueado: true,
    aprovado_agencia_em: "2024-05-28T10:00:00Z",
    aprovado_agencia_por: "Beatriz Costa — TAGMOB",
    aprovado_cliente_em: null,
    aprovado_cliente_por: null,
    comentarios: [
      {
        id: "c1",
        autor: "Beatriz Costa",
        perfil: "AGENCIA",
        mensagem: "Peça revisada conforme feedback da última reunião. CTA ajustado para 'Solicite uma visita'.",
        criado_em: "2024-05-28T10:05:00Z",
      },
    ],
    campos_editaveis: [
      { id: "f1", label: "Metragem disponível", tipo: "TEXTO", valor_atual: "250 a 1.200m²", placeholder: "Xm² a Ym²", max_chars: 20 },
      { id: "f2", label: "CTA",                 tipo: "CTA",   valor_atual: "SOLICITE UMA VISITA", placeholder: "CTA", max_chars: 25 },
    ],
    dimensoes: "1080 × 1080px",
    criado_em: "2024-05-27",
  },
];

export function getEmpreendimento(id: string): Empreendimento | undefined {
  return MOCK_EMPREENDIMENTOS.find((e) => e.id === id);
}

export function getAssetsEmpreendimento(empreendimentoId: string): AssetOS[] {
  return MOCK_ASSETS.filter((a) => a.empreendimento_id === empreendimentoId);
}

export function getEstrategia(empreendimentoId: string): EstrategiaOS | undefined {
  return MOCK_ESTRATEGIA[empreendimentoId];
}

export function getDesignSystem(empreendimentoId: string): DesignSystemOS | undefined {
  return MOCK_DESIGN_SYSTEM[empreendimentoId];
}

// ─── HUB DO ECOSSISTEMA ───────────────────────────────────────────────────────

export const MOCK_EXCLUSIVIDADES: ExclusividadeRegra[] = [
  { id: "exc-001", marca_id: "mrc-001", tipo: "BAIRRO",         alvo: "Jardins",      vigencia_inicio: "2024-01-01", vigencia_fim: "2024-12-31", ativa: true  },
  { id: "exc-002", marca_id: "mrc-001", tipo: "BAIRRO",         alvo: "Itaim Bibi",   vigencia_inicio: "2024-01-01", vigencia_fim: "2024-12-31", ativa: true  },
  { id: "exc-003", marca_id: "mrc-002", tipo: "PADRAO",         alvo: "SUPER_LUXO",   vigencia_inicio: "2024-03-01", vigencia_fim: null,          ativa: true  },
  { id: "exc-004", marca_id: "mrc-003", tipo: "EMPREENDIMENTO", alvo: "emp-001",       vigencia_inicio: "2024-04-01", vigencia_fim: "2025-03-31", ativa: true  },
  { id: "exc-005", marca_id: "mrc-005", tipo: "REGIAO",         alvo: "Zona Sul SP",  vigencia_inicio: "2024-02-01", vigencia_fim: "2024-08-31", ativa: false },
];

export const MOCK_PRODUTOS_INDUSTRIA: ProdutoIndustria[] = [
  {
    id: "prd-001",
    marca_id: "mrc-001",
    marca_nome: "Portobello",
    nome: "Coleção Marfim Travertino",
    categoria: "Pisos & Revestimentos",
    subcategoria: "Porcelanato",
    descricao: "Porcelanato 90×90cm efeito travertino. Absorção ≤ 0,1%. Indicado para áreas internas de alto tráfego.",
    imagem_url: "/mock/prod-portobello-01.jpg",
    especificacoes: { "Formato": "90×90cm", "PEI": "5", "Acabamento": "Polido", "Coleção": "Travertino" },
    status: "EXCLUSIVO",
    cpv_brl: 0.45,
    cpa_brl: 280,
    total_specs: 47,
    total_impressoes: 12_400,
    total_leads: 38,
    exclusividades: [MOCK_EXCLUSIVIDADES[0], MOCK_EXCLUSIVIDADES[1]],
  },
  {
    id: "prd-002",
    marca_id: "mrc-001",
    marca_nome: "Portobello",
    nome: "Coleção Concrete Oslo",
    categoria: "Pisos & Revestimentos",
    subcategoria: "Porcelanato Técnico",
    descricao: "Porcelanato 60×120cm efeito concreto. Textura suave. Ideal para ambientes contemporâneos minimalistas.",
    imagem_url: "/mock/prod-portobello-02.jpg",
    especificacoes: { "Formato": "60×120cm", "PEI": "4", "Acabamento": "Acetinado", "Coleção": "Concrete" },
    status: "ATIVO",
    cpv_brl: 0.38,
    cpa_brl: 245,
    total_specs: 31,
    total_impressoes: 8_900,
    total_leads: 22,
    exclusividades: [],
  },
  {
    id: "prd-003",
    marca_id: "mrc-002",
    marca_nome: "Deca",
    nome: "Linha Targa Banheira Freestanding",
    categoria: "Louças & Metais",
    subcategoria: "Banheiras",
    descricao: "Banheira freestanding em acrílico sanitário de alta resistência. 170×75cm. Design contemporâneo de assinatura.",
    imagem_url: "/mock/prod-deca-01.jpg",
    especificacoes: { "Dimensão": "170×75×58cm", "Material": "Acrílico sanitário", "Cor": "Branco brilhante", "Instalação": "Freestanding" },
    status: "EXCLUSIVO",
    cpv_brl: 0.72,
    cpa_brl: 520,
    total_specs: 19,
    total_impressoes: 5_300,
    total_leads: 28,
    exclusividades: [MOCK_EXCLUSIVIDADES[2]],
  },
  {
    id: "prd-004",
    marca_id: "mrc-002",
    marca_nome: "Deca",
    nome: "Torneira Cube Monocomando",
    categoria: "Louças & Metais",
    subcategoria: "Torneiras",
    descricao: "Torneira monocomando para lavatório. Acabamento cromado escovado. Aerador com regulagem de vazão.",
    imagem_url: "/mock/prod-deca-02.jpg",
    especificacoes: { "Acabamento": "Cromado escovado", "Tipo": "Monocomando", "Pressão": "10–50 PSI", "Vazão": "6 L/min" },
    status: "ATIVO",
    cpv_brl: 0.29,
    cpa_brl: 190,
    total_specs: 64,
    total_impressoes: 18_700,
    total_leads: 51,
    exclusividades: [],
  },
  {
    id: "prd-005",
    marca_id: "mrc-003",
    marca_nome: "Poliform",
    nome: "Cozinha Artex — Lacado Matte",
    categoria: "Mobiliário de Design",
    subcategoria: "Cozinhas",
    descricao: "Sistema de cozinha com portas lacadas fosco bianco. Puxadores integrados e interior personalizado.",
    imagem_url: "/mock/prod-poliform-01.jpg",
    especificacoes: { "Acabamento": "Lacado fosco", "Sistema": "Modular", "Ilha": "Opcional", "Perfil": "Alto Padrão" },
    status: "EXCLUSIVO",
    cpv_brl: 1.20,
    cpa_brl: 980,
    total_specs: 12,
    total_impressoes: 3_800,
    total_leads: 16,
    exclusividades: [MOCK_EXCLUSIVIDADES[3]],
  },
  {
    id: "prd-006",
    marca_id: "mrc-004",
    marca_nome: "Intelbras",
    nome: "Central de Automação Residencial AMI 300",
    categoria: "Automação Residencial",
    subcategoria: "Centrais de Automação",
    descricao: "Central de automação para controle de iluminação, climatização, segurança e áudio distribuído. Compatível com Alexa e Google Home.",
    imagem_url: "/mock/prod-intelbras-01.jpg",
    especificacoes: { "Protocolo": "Wi-Fi + ZigBee", "Pontos": "até 128", "App": "iOS e Android", "Integração": "Alexa, Google Home" },
    status: "PAUSADO",
    cpv_brl: 0.55,
    cpa_brl: 420,
    total_specs: 8,
    total_impressoes: 2_100,
    total_leads: 9,
    exclusividades: [],
  },
];

export const MOCK_PROJETOS_ARQUITETO: ProjetoArquiteto[] = [
  {
    id: "proj-001",
    nome: "Decorado Tipo 245m² — Torre A",
    arquiteto_nome: "Carolina Fernandes",
    arquiteto_creci: "A-12345/SP",
    empreendimento_id: "emp-001",
    empreendimento_nome: "Reserva Jardins",
    descricao: "Projeto completo do apartamento decorado com conceito contemporâneo orgânico. Tons terrosos, travertino e madeira natural.",
    ambientes: ["Sala de Estar", "Sala de Jantar", "Cozinha Integrada", "Suíte Master", "Suíte 2", "Lavabo"],
    specs_count: 18,
    marcas_specs: ["Portobello", "Deca", "Poliform"],
    status: "EM_ANDAMENTO",
    criado_em: "2024-05-10",
  },
  {
    id: "proj-002",
    nome: "Área de Lazer — Rooftop",
    arquiteto_nome: "Ricardo Almeida",
    arquiteto_creci: "A-67890/SP",
    empreendimento_id: "emp-001",
    empreendimento_nome: "Reserva Jardins",
    descricao: "Projeto do rooftop com piscina, deck, jardim suspenso e área gourmet.",
    ambientes: ["Piscina", "Deck", "Área Gourmet", "Jardim Suspenso"],
    specs_count: 7,
    marcas_specs: ["Portobello", "Deca"],
    status: "ENTREGUE",
    criado_em: "2024-04-20",
  },
  {
    id: "proj-003",
    nome: "Lobby e Recepção",
    arquiteto_nome: "Carolina Fernandes",
    arquiteto_creci: "A-12345/SP",
    empreendimento_id: "emp-002",
    empreendimento_nome: "Faria Lima Corporate",
    descricao: "Lobby corporativo com identidade visual premium. Pedra natural, iluminação cênica e painéis de identidade.",
    ambientes: ["Lobby Principal", "Recepção", "Circulação"],
    specs_count: 11,
    marcas_specs: ["Portobello", "Intelbras"],
    status: "RASCUNHO",
    criado_em: "2024-06-01",
  },
];

export const MOCK_ESPECIFICACOES: EspecificacaoArquiteto[] = [
  {
    id: "spc-001",
    projeto_id: "proj-001",
    arquiteto_nome: "Carolina Fernandes",
    empreendimento_id: "emp-001",
    empreendimento_nome: "Reserva Jardins",
    produto: MOCK_PRODUTOS_INDUSTRIA[0],
    ambiente: "Sala de Estar",
    quantidade: 180,
    observacao: "Aplicar em junta perdida 3mm. Rejunte bege escuro.",
    criado_em: "2024-05-15",
    lead_gerado: true,
  },
  {
    id: "spc-002",
    projeto_id: "proj-001",
    arquiteto_nome: "Carolina Fernandes",
    empreendimento_id: "emp-001",
    empreendimento_nome: "Reserva Jardins",
    produto: MOCK_PRODUTOS_INDUSTRIA[2],
    ambiente: "Suíte Master",
    quantidade: 1,
    observacao: "Posicionamento central, distância mínima de 80cm das paredes.",
    criado_em: "2024-05-16",
    lead_gerado: true,
  },
  {
    id: "spc-003",
    projeto_id: "proj-001",
    arquiteto_nome: "Carolina Fernandes",
    empreendimento_id: "emp-001",
    empreendimento_nome: "Reserva Jardins",
    produto: MOCK_PRODUTOS_INDUSTRIA[4],
    ambiente: "Cozinha Integrada",
    quantidade: 1,
    observacao: "Ilha central em ilha 3,2m. Coifa industrial embutida no forro.",
    criado_em: "2024-05-18",
    lead_gerado: false,
  },
];

export const MOCK_METRICAS_ADTECH: MetricaAdTech[] = [
  {
    marca_id: "mrc-001",
    marca_nome: "Portobello",
    periodo: "Jun/2024",
    impressoes: 12_400,
    cliques: 1_488,
    specs_arquitetos: 47,
    leads: 38,
    ctr: 12.0,
    receita_brl: 8_750,
    conversoes: 12,
  },
  {
    marca_id: "mrc-002",
    marca_nome: "Deca",
    periodo: "Jun/2024",
    impressoes: 9_100,
    cliques: 728,
    specs_arquitetos: 38,
    leads: 41,
    ctr: 8.0,
    receita_brl: 6_320,
    conversoes: 9,
  },
  {
    marca_id: "mrc-003",
    marca_nome: "Poliform",
    periodo: "Jun/2024",
    impressoes: 3_800,
    cliques: 494,
    specs_arquitetos: 12,
    leads: 16,
    ctr: 13.0,
    receita_brl: 4_900,
    conversoes: 5,
  },
  {
    marca_id: "mrc-004",
    marca_nome: "Intelbras",
    periodo: "Jun/2024",
    impressoes: 2_100,
    cliques: 126,
    specs_arquitetos: 8,
    leads: 9,
    ctr: 6.0,
    receita_brl: 1_890,
    conversoes: 2,
  },
  {
    marca_id: "mrc-005",
    marca_nome: "Eliane",
    periodo: "Jun/2024",
    impressoes: 5_600,
    cliques: 448,
    specs_arquitetos: 22,
    leads: 19,
    ctr: 8.0,
    receita_brl: 3_120,
    conversoes: 6,
  },
];

export const HUB_METRICAS: HubMetrica = {
  ativos_em_circulacao: 142,
  leads_gerados_mes: 147,
  receita_adtech_mes: 24_980,
  corretores_ativos: 38,
  arquitetos_ativos: 7,
  marcas_ativas: 4,
  specs_mes: 127,
  empreendimentos_ativos: 5,
};

export function getMarcaById(id: string): (typeof MOCK_MARCAS)[0] | undefined {
  return MOCK_MARCAS.find((m) => m.id === id);
}

export function getProdutosMarca(marcaId: string): ProdutoIndustria[] {
  return MOCK_PRODUTOS_INDUSTRIA.filter((p) => p.marca_id === marcaId);
}

export function getMetricaMarca(marcaId: string): MetricaAdTech | undefined {
  return MOCK_METRICAS_ADTECH.find((m) => m.marca_id === marcaId);
}

export function getEspecificacoesProjeto(projetoId: string): EspecificacaoArquiteto[] {
  return MOCK_ESPECIFICACOES.filter((e) => e.projeto_id === projetoId);
}
